#!/usr/bin/php
<?php

// MySQL

$config = parse_ini_file( '../config/config.ini', true);

$MySQL_User = $config['mysql']['username'];
$MySQL_Pass = $config['mysql']['password'];
$MySQL_DBName = 'gameStats';

// SQLite

$SQLite_Path = '../data/';

////////////////////////////////////////////////////////////////////////////

$PDO_SQLite = NULL;
$PDO_MySQL = NULL;

function makeArrayRequest( $array) {
	$string = '';
	foreach( $array as $value) { $string .= '`'.$value.'`, '; }
	return substr_replace($string , '', -2);
}

function request( $PDO, $string) {
  $data = $PDO->query($string);
  $data->execute();
  return $data->fetchAll(PDO::FETCH_ASSOC);
}

function sqlite_request( $string) {
  global $PDO_SQLite;
  return request( $PDO_SQLite, $string);
}

function mysql_request( $string) {
  global $PDO_MySQL;
  return request( $PDO_MySQL, $string);
}

function generateQueries( $tableName, $references, $results) {
	$sql_queries = Array();
	foreach( $results as $current) {
		$sql = 'INSERT INTO `'.$tableName.'` ( '.makeArrayRequest( $references).') VALUES ( ';
		
    $values = Array();
		foreach( $references as $column) {
			$values[] = $current[$column];
		}
		
		$sql .= makeArrayRequest( $values);
		$sql_queries[] = $sql;
	}
	
	return $sql_queries;
}

function launch_queries( $queries) {
	print_r( $queries);
	exit();
}

$PDO_MySQL = new PDO('mysql:host=localhost;dbname='.$MySQL_DBName, $MySQL_User, $MySQL_Pass);

// SQLite databases init
$SQLite_Databases = glob( $SQLite_Path. '*.sqlite');

// MySQL init
$tables = Array();
$text_cols = Array();
$stats_cols = Array();
$result = mysql_request( 'SHOW TABLES;');
foreach( $result as $current) {
	if( $current['Tables_in_gameStats'] != 'i18n') {
		$tables[] = $current['Tables_in_gameStats'];
	}
}

foreach( $tables as $table) {

	// text cols
	$result = mysql_request( "SELECT COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'gameStats' AND TABLE_NAME = '$table' AND REFERENCED_TABLE_NAME = 'i18n'");
	
	if( count( $result) > 0) {
		$text_cols[$table] = Array();
		foreach( $result as $current) {
			$text_cols[$table][] = $current['COLUMN_NAME'];
		}
	}
	
	// stats cols
	$result = mysql_request( "SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'gameStats' AND TABLE_NAME = '$table';");
	
	$stats_cols[$table] = Array();
	foreach( $result as $current) {
		if( $text_cols[$table] != NULL && !in_array( $current['COLUMN_NAME'], $text_cols[$table])) {
			$stats_cols[$table][] = $current['COLUMN_NAME'];
		}
	}
}

// Let's GO !
		/*
		if( !$stats || $stats_inProgress) {
		}
		*/
		
$stats = false;
foreach( $SQLite_Databases as $SQLite_Database) {
	$PDO_SQLite = new PDO('sqlite:'.$SQLite_Database);

	$sql_queries = Array();
	foreach( $tables as $table) {
		$result = sqlite_request( "SELECT * FROM $table");
		
		if( !$stats) {
			array_merge( $sql_queries, generateQueries( $table, $stats_cols[$table], $result));
			$stats = true;
		}
		
		array_merge( $sql_queries, generateQueries( $table, $text_cols[$table], $result));
	}

	launch_queries( $sql_queries);
}

?>

