#!/usr/bin/php
<?php

// MySQL

$config = parse_ini_file( '../config/config.ini', true);

$MySQL_User = $config['mysql']['username'];
$MySQL_Pass = $config['mysql']['password'];
$MySQL_DBName = 'gameStats';

// SQLite

$SQLite_Path = '../data/';

////////////////////////////////////////////////////////////////////////////

$PDO_SQLite = NULL;
$PDO_MySQL = NULL;

function request( $PDO, $string) {
  $data = $PDO->query($query);
  $data->execute();
  return $data->fetchAll(PDO::FETCH_ASSOC);
}

function sqlite_request( $string) {
  global $PDO_SQLite;
  return request( $PDO_SQLite, $string);
}

function mysql_request( $string) {
  global $PDO_MySQL;
  return request( $PDO_MySQL, $string);
}

$PDO_MySQL = new PDO('mysql:host=localhost;dbname='.$MySQL_DBName, $MySQL_User, $MySQL_Pass);

// SQLite databases init
$SQLite_Databases = glob( $SQLite_Path. '*.sqlite');

// MySQL init
$tables = Array();
$text_cols = Array();
$stats_cols = Array();
$result = mysql_request( 'SHOW TABLES;');
foreach( $result as $current) {
	if( $current['Tables_in_gameStats'] != 'i18n') {
		$tables[] = $current['Tables_in_gameStats'];
	}
}

foreach( $tables as $table) {

	// text cols
	$result = mysql_request( "SELECT COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'gameStats' AND TABLE_NAME = '$table' AND REFERENCED_TABLE_NAME = 'i18n'");
	
	if( count( $result) > 0) {
		$text_cols[$table] = Array();
		foreach( $result as $current) {
			$text_cols[$table][] = $current['COLUMN_NAME'];
		}
	}
	
	// stats cols
	$result = mysql_request( "SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'gameStats' AND TABLE_NAME = '$table';");
	
	$stats_cols[$table] = Array();
	foreach( $result as $current) {
		if( !in_array( $current['COLUMN_NAME'], $text_cols[$table])) {
			$stats_cols[$table][] = $current['COLUMN_NAME'];
		}
	}
}

/*
// Let's GO !
$stats = false;
foreach( $SQLite_Databases as $SQLite_Database) {
  $PDO_SQLite = new PDO('sqlite:'.$SQLite_Database);

  if( !$stats) {
    // take all stats
    
    
    
    $stats = true;
  }

  // take all text
}
*/

?>

